USERNAME = "daya-retail"
PASSWORD_HASH = "$2b$12$wCiIN6rkQfZgU2iOlR13tefVk8kC./N1D87DTkcy1J271e0/MZHk6"
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDk4OTQxNzEsImlkIjoiNTE3OTIwZDYtODE0Zi00MDA2LWJjMTQtNDYxNWM0NzkzMjQ0IiwicmlkIjoiYmU2YTdiODUtM2FhZS00Y2Y0LWFlZDAtMTRkZTMxOWU4ZjNmIn0.MQXZa4OS0h0IzSMzSsg5dg-XHO7phUwgfWlQRT3H9olPdSUnk8L0OrWaKQCLNzhDH3mVPmwl8Q5g3KABPD2mCw"
TURSO_DB_URL = "https://db-wh-wisedud2u.aws-ap-northeast-1.turso.io"